[tox]
envlist = py37,py38,py39,py310,py311,py312,pypy3
isolated_build = True

[testenv]
deps =
    pytest>=6.0
    pytest-cov
    coverage
extras = test
commands =
    pytest {posargs:tests} --cov=httpbin
    coverage report

[pytest]
testpaths = tests
python_files = test_*.py
addopts = -v --tb=short
